const packageName = 'appointments'


export const GET_APPOINTMENTS = `${packageName}/GET_APPOINTMENTS`
export const GET_APPOINTMENTS_SUCCESS = `${packageName}/GET_APPOINTMENTS_SUCCESS`
export const GET_APPOINTMENTS_FAIL = `${packageName}/GET_APPOINTMENTS_FAIL`

export const GET_APPOINTMENT = `${packageName}/GET_APPOINTMENT`
export const GET_APPOINTMENT_SUCCESS = `${packageName}/GET_APPOINTMENT_SUCCESS`
export const GET_APPOINTMENT_FAIL = `${packageName}/GET_APPOINTMENT_FAIL`

export const CREATE_APPOINTMENT = `${packageName}/CREATE_APPOINTMENT`
export const CREATE_APPOINTMENT_SUCCESS = `${packageName}/CREATE_APPOINTMENT_SUCCESS`
export const CREATE_APPOINTMENT_FAIL = `${packageName}/CREATE_APPOINTMENT_FAIL`

export const UPDATE_APPOINTMENT = `${packageName}/UPDATE_APPOINTMENT`
export const UPDATE_APPOINTMENT_SUCCESS = `${packageName}/UPDATE_APPOINTMENT_SUCCESS`
export const UPDATE_APPOINTMENT_FAIL = `${packageName}/UPDATE_APPOINTMENT_FAIL`