name: Production Build
on:
  pull_request:
  push:
    branches:
      - deploy

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
        - uses: actions/checkout@v1
        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v1
          with:
            node-version: ${{ matrix.node-version }}
        - name: Yarn Install
              run: |
                yarn install
            - name: Production Build
              run: |
                yarn build
            - name: Deploy to S3
                  uses: jakejarvis/s3-sync-action@master
                  with:
                    args: --acl public-read --delete
                  env:
                    AWS_S3_BUCKET: ${{ secrets.AWS_STAGING_BUCKET_NAME }}
                    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                    AWS_REGION: ${{ secrets.AWS_REGION }}
                    SOURCE_DIR: "build"


AKIAVYSFHLAWGFFCHAS6

TTxQzFhOmOaRO6MEB5WVQ36e44R5U9ZUTrlW/KYd
